version: '3'
services:
  openldap:
    image: osixia/openldap:stable
    container_name: openldap
    env_file:
      - .env
    restart: always
    environment:
      LDAP_LOG_LEVEL: ${LDAP_LOG_LEVEL}
      LDAP_ORGANISATION: ${LDAP_ORGANISATION}
      LDAP_DOMAIN: ${LDAP_DOMAIN}
      LDAP_BASE_DN: ${LDAP_BASE_DN}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      LDAP_CONFIG_PASSWORD: ${LDAP_CONFIG_PASSWORD}
      LDAP_READONLY_USER: ${LDAP_READONLY_USER}
      LDAP_READONLY_USER_USERNAME: ${LDAP_READONLY_USER_USERNAME}
      LDAP_READONLY_USER_PASSWORD: ${LDAP_READONLY_USER_PASSWORD}
      LDAP_RFC2307BIS_SCHEMA: ${LDAP_RFC2307BIS_SCHEMA}
      LDAP_BACKEND: ${LDAP_BACKEND}
      LDAP_TLS: ${LDAP_TLS}
      #LDAP_TLS_CRT_FILENAME: ${LDAP_TLS_CRT_FILENAME}
      #LDAP_TLS_KEY_FILENAME: ${LDAP_TLS_KEY_FILENAME}
      #LDAP_TLS_DH_PARAM_FILENAME: ${LDAP_TLS_DH_PARAM_FILENAME}
      #LDAP_TLS_CA_CRT_FILENAME: ${LDAP_TLS_CA_CRT_FILENAME}
      LDAP_TLS_ENFORCE: ${LDAP_TLS_ENFORCE}
      LDAP_TLS_CIPHER_SUITE: ${LDAP_TLS_CIPHER_SUITE}
      LDAP_TLS_VERIFY_CLIENT: ${LDAP_TLS_VERIFY_CLIENT}
      LDAP_REPLICATION: ${LDAP_REPLICATION}
      #LDAP_REPLICATION_CONFIG_SYNCPROV: ${LDAP_REPLICATION_CONFIG_SYNCPROV}
      #LDAP_REPLICATION_DB_SYNCPROV: ${LDAP_REPLICATION_DB_SYNCPROV}
      #LDAP_REPLICATION_HOSTS: ${LDAP_REPLICATION_HOSTS}
      KEEP_EXISTING_CONFIG: ${KEEP_EXISTING_CONFIG}
      LDAP_REMOVE_CONFIG_AFTER_SETUP: ${LDAP_REMOVE_CONFIG_AFTER_SETUP}
      LDAP_SSL_HELPER_PREFIX: ${LDAP_SSL_HELPER_PREFIX}
    tty: true
    stdin_open: true
    volumes:
      - ldap_db:/var/lib/ldap
      - ldap_conf:/etc/ldap/slapd.d
      - ldap_certs:/container/service/slapd/assets/certs/
    # Enable if need access outside docker network
    #ports:
    #   - "389:389"
    #   - "636:636"
    # For replication to work correctly, domainname and hostname must be
    # set correctly so that "hostname"."domainname" equates to the
    # fully-qualified domain name for the host.
    domainname: ${LDAP_DOMAIN}
    hostname: ${LDAP_HOSTS}

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    restart: always
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ${LDAP_HOSTS}
      PHPLDAPADMIN_HTTPS: ${PHPLDAPADMIN_HTTPS}
    volumes:
      - phpldapadmin:/var/www/phpldapadmin
    labels: # Traefik configuration.
     #
      - traefik.http.routers.phpldapadmin.rule=Host(`${VIRTUAL_HOST_LDAP}`)
      - traefik.http.routers.phpldapadmin.tls=true
      - traefik.http.routers.phpldapadmin.tls.certresolver=lets-encrypt
      - traefik.http.routers.phpldapadmin.service=phpldapadmin-service
      - traefik.http.services.phpldapadmin-service.loadbalancer.server.port=${VIRTUAL_PORT_LDAP}
    depends_on:
      - openldap

volumes:
   ldap_db:
   ldap_conf:
   ldap_certs:
   phpldapadmin:
  
networks:
  default:
    external:
      name: webproxy