version: '3'

services:
 traefik:
    restart: always
    image: traefik:2.4
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./traefik.toml:/traefik.toml"
      - "./traefik_dynamic.toml:/traefik_dynamic.toml"
      # add primission - chmod 600 acme.json
      - "./acme.json:/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
# create network -  docker network create webproxy
networks:
  default:
    external:
      name: webproxy